use support;
Insert Into Topic(topic_name) Values("Проблема со связью");
Insert Into Topic(topic_name) Values("Проблема с телефоном");
Insert Into Topic(topic_name) Values("Проблема с расчетами, начислениями");
Insert Into Topic(topic_name) Values("Другое");
Insert Into Inquiry(customer_name, topic_id, create_date, description) Values ("Олег", 1, "2015-09-21", "Тестовое обращение");
Insert Into Inquiry(customer_name, topic_id, create_date, description) Values ("Тест", 2, "2015-09-21", "Тестовое обращение");
Insert Into Inquiry(customer_name, topic_id, create_date, description) Values ("Тест", 3, "2015-09-21", "Тестовое обращение");
Insert Into Inquiry(customer_name, topic_id, create_date, description) Values ("Тест", 2, "2015-09-21", "Тестовое обращение");
Insert Into Inquiry(customer_name, topic_id, create_date, description) Values ("Тест", 4, "2015-09-21", "Тестовое обращение");
Insert Into AttributeOfInquiry(attribute_name, attribute_value, inquiry_id) Values ("Город", "Борисов", 1);
Insert Into AttributeOfInquiry(attribute_name, attribute_value, inquiry_id) Values ("Атрибут1", "Значение1", 1);
Insert Into AttributeOfInquiry(attribute_name, attribute_value, inquiry_id) Values ("Атрибут2", "Значение2", 1);
Insert Into AttributeOfInquiry(attribute_name, attribute_value, inquiry_id) Values ("Атрибут1", "Значение1", 4);
Insert Into AttributeOfInquiry(attribute_name, attribute_value, inquiry_id) Values ("Атрибут2", "Значение2", 4);